import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import MessagePopupNotifications from "../components/MessagePopupNotifications";
// ...existing code...

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // The correct way is to render MessagePopupNotifications inside GroupsPage, where you have access to allGroups, setSelectedGroup, setActiveTab.
  // In layout.tsx, just wrap with AuthProvider and render children:
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* Optionally add <Header /> here */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
